### PR TITLE
The Basics

### PR DESCRIPTION
**Pull request by haylinmoore**
I added a basic UI and some function to add chat messages.

Live View https://git.hampton.pw/WebApp/

### CODE REVIEW

**Comment by pen-and-paper** [comment]
It looks pretty good! Are you going to add the logo?

**Comment by haylinmoore** [comment]
make a PR on my fork @pen-and-paper

**Comment by pen-and-paper** [comment]
I don't know what that means...

**Comment by haylinmoore** [comment]
I was saying go to my fork make a PR with the logo or the edit you want, so then it can be added to this pull request to the main WebApp. Sorry I would do it but I am busy rn

**Comment by pen-and-paper** [comment]
Okay :)

**Comment by encloinc** [comment]
looks nice but it needs more (hence the basics)

**Comment by pen-and-paper** [comment]
Done, I think https://github.com/pen-and-paper/WebApp/commit/cb156de631b72428c8cc5b28888d00e00236555c

**Pull request merged**
